/** Auto-generated by scripts/generate-pack-inventory.mjs - do not edit. */
export interface PackGlbEntry {
  pack: string;
  file: string;
}

export const PACK_GLB_INVENTORY: readonly PackGlbEntry[] = [
  {
    "pack": "animals",
    "file": "Bear.glb"
  },
  {
    "pack": "animals",
    "file": "Bee.glb"
  },
  {
    "pack": "animals",
    "file": "Bird.glb"
  },
  {
    "pack": "animals",
    "file": "Cat.glb"
  },
  {
    "pack": "animals",
    "file": "Chicken.glb"
  },
  {
    "pack": "animals",
    "file": "Crab.glb"
  },
  {
    "pack": "animals",
    "file": "Dog.glb"
  },
  {
    "pack": "animals",
    "file": "Duck.glb"
  },
  {
    "pack": "animals",
    "file": "Fish.glb"
  },
  {
    "pack": "animals",
    "file": "Frog.glb"
  },
  {
    "pack": "animals",
    "file": "Penguin.glb"
  },
  {
    "pack": "animals",
    "file": "Rabbit.glb"
  },
  {
    "pack": "animals",
    "file": "Snake.glb"
  },
  {
    "pack": "animals",
    "file": "Spider.glb"
  },
  {
    "pack": "animals",
    "file": "Turkey vulture.glb"
  },
  {
    "pack": "animals",
    "file": "Turtle.glb"
  },
  {
    "pack": "animals",
    "file": "Wolf.glb"
  },
  {
    "pack": "camping",
    "file": "Campfire.glb"
  },
  {
    "pack": "camping",
    "file": "Fire.glb"
  },
  {
    "pack": "camping",
    "file": "Log.glb"
  },
  {
    "pack": "camping",
    "file": "Rock.glb"
  },
  {
    "pack": "camping",
    "file": "Tent.glb"
  },
  {
    "pack": "camping",
    "file": "Tree.glb"
  },
  {
    "pack": "cars",
    "file": "Car.glb"
  },
  {
    "pack": "cars",
    "file": "Police Car.glb"
  },
  {
    "pack": "cars",
    "file": "Sports Car.glb"
  },
  {
    "pack": "cars",
    "file": "SUV.glb"
  },
  {
    "pack": "cars",
    "file": "Taxi.glb"
  },
  {
    "pack": "farm-animals",
    "file": "Llama.glb"
  },
  {
    "pack": "farm-animals",
    "file": "Pig.glb"
  },
  {
    "pack": "farm-animals",
    "file": "Pug.glb"
  },
  {
    "pack": "food",
    "file": "Apple Green.glb"
  },
  {
    "pack": "food",
    "file": "Banana.glb"
  },
  {
    "pack": "food",
    "file": "Bottle.glb"
  },
  {
    "pack": "food",
    "file": "Bread.glb"
  },
  {
    "pack": "food",
    "file": "Burger.glb"
  },
  {
    "pack": "food",
    "file": "Carrot.glb"
  },
  {
    "pack": "food",
    "file": "Chicken Leg.glb"
  },
  {
    "pack": "food",
    "file": "Cooking Pot.glb"
  },
  {
    "pack": "food",
    "file": "Cupcake.glb"
  },
  {
    "pack": "food",
    "file": "Donut.glb"
  },
  {
    "pack": "food",
    "file": "Egg.glb"
  },
  {
    "pack": "food",
    "file": "Fries.glb"
  },
  {
    "pack": "food",
    "file": "Frying Pan.glb"
  },
  {
    "pack": "food",
    "file": "Hotdog.glb"
  },
  {
    "pack": "food",
    "file": "Ice Cream.glb"
  },
  {
    "pack": "food",
    "file": "Pancakes Stack.glb"
  },
  {
    "pack": "food",
    "file": "Pizza.glb"
  },
  {
    "pack": "food",
    "file": "Soda.glb"
  },
  {
    "pack": "food",
    "file": "Steak.glb"
  },
  {
    "pack": "food",
    "file": "Tomato.glb"
  },
  {
    "pack": "furniture",
    "file": "Bar Stool.glb"
  },
  {
    "pack": "furniture",
    "file": "Bathroom Cabinet Drawe.glb"
  },
  {
    "pack": "furniture",
    "file": "Bathroom Cabinet.glb"
  },
  {
    "pack": "furniture",
    "file": "Bathroom Mirror.glb"
  },
  {
    "pack": "furniture",
    "file": "Bathroom Sink Square.glb"
  },
  {
    "pack": "furniture",
    "file": "Bathroom Sink.glb"
  },
  {
    "pack": "furniture",
    "file": "Bathtub.glb"
  },
  {
    "pack": "furniture",
    "file": "Bear.glb"
  },
  {
    "pack": "furniture",
    "file": "Bed Bunk.glb"
  },
  {
    "pack": "furniture",
    "file": "Bed Double.glb"
  },
  {
    "pack": "furniture",
    "file": "Bed Single.glb"
  },
  {
    "pack": "furniture",
    "file": "Bench Cushion Low.glb"
  },
  {
    "pack": "furniture",
    "file": "Bench Cushion.glb"
  },
  {
    "pack": "furniture",
    "file": "Bench.glb"
  },
  {
    "pack": "furniture",
    "file": "Bookcase Closed Doors.glb"
  },
  {
    "pack": "furniture",
    "file": "Bookcase Closed Wide.glb"
  },
  {
    "pack": "furniture",
    "file": "Bookcase Closed.glb"
  },
  {
    "pack": "furniture",
    "file": "Bookcase Open Low.glb"
  },
  {
    "pack": "furniture",
    "file": "Bookcase Open.glb"
  },
  {
    "pack": "furniture",
    "file": "BookcaseWithBooks.glb"
  },
  {
    "pack": "furniture",
    "file": "Books.glb"
  },
  {
    "pack": "furniture",
    "file": "Cabinet Bed Drawer Tabl.glb"
  },
  {
    "pack": "furniture",
    "file": "Cabinet Bed Drawer.glb"
  },
  {
    "pack": "furniture",
    "file": "Cabinet Bed.glb"
  },
  {
    "pack": "furniture",
    "file": "Cabinet Television Doo.glb"
  },
  {
    "pack": "furniture",
    "file": "Cabinet Television.glb"
  },
  {
    "pack": "furniture",
    "file": "Cardboard Box Closed.glb"
  },
  {
    "pack": "furniture",
    "file": "Cardboard Box Open.glb"
  },
  {
    "pack": "furniture",
    "file": "Ceiling Fan.glb"
  },
  {
    "pack": "furniture",
    "file": "Chair Cushion.glb"
  },
  {
    "pack": "furniture",
    "file": "Chair Desk.glb"
  },
  {
    "pack": "furniture",
    "file": "Chair Modern Cushion.glb"
  },
  {
    "pack": "furniture",
    "file": "Chair Modern Frame Cush.glb"
  },
  {
    "pack": "furniture",
    "file": "Chair Rounded.glb"
  },
  {
    "pack": "furniture",
    "file": "Chair.glb"
  },
  {
    "pack": "furniture",
    "file": "Coat Rack Standing.glb"
  },
  {
    "pack": "furniture",
    "file": "Coat Rack.glb"
  },
  {
    "pack": "furniture",
    "file": "Computer Keyboard.glb"
  },
  {
    "pack": "furniture",
    "file": "Computer Screen.glb"
  },
  {
    "pack": "furniture",
    "file": "Desk Corner.glb"
  },
  {
    "pack": "furniture",
    "file": "Desk.glb"
  },
  {
    "pack": "furniture",
    "file": "Doorway Front.glb"
  },
  {
    "pack": "furniture",
    "file": "Doorway Open.glb"
  },
  {
    "pack": "furniture",
    "file": "Doorway.glb"
  },
  {
    "pack": "furniture",
    "file": "Dryer.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Bar.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Blender.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Cabinet Corner.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Cabinet Drawer.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Cabinet Upper.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Cabinet Upperc.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Cabinet Upperl.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Cabinet.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Coffee Machine.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Fridge Built In.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Fridge Large.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Fridge Small.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Fridge.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Hood Large.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Microwave.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Sink.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Stove Electric.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Stove Hood.glb"
  },
  {
    "pack": "furniture",
    "file": "Kitchen Stove.glb"
  },
  {
    "pack": "furniture",
    "file": "Lamp Round Floor.glb"
  },
  {
    "pack": "furniture",
    "file": "Lamp Round Table.glb"
  },
  {
    "pack": "furniture",
    "file": "Lamp Square Ceiling.glb"
  },
  {
    "pack": "furniture",
    "file": "Lamp Square Floor.glb"
  },
  {
    "pack": "furniture",
    "file": "Lamp Square Table.glb"
  },
  {
    "pack": "furniture",
    "file": "Lamp Wall.glb"
  },
  {
    "pack": "furniture",
    "file": "Laptop.glb"
  },
  {
    "pack": "furniture",
    "file": "Lounge Chair-PImRvMqW1O.glb"
  },
  {
    "pack": "furniture",
    "file": "Lounge Design Chair.glb"
  },
  {
    "pack": "furniture",
    "file": "Lounge Design Sofa Corn.glb"
  },
  {
    "pack": "furniture",
    "file": "Lounge Design Sofa.glb"
  },
  {
    "pack": "furniture",
    "file": "Lounge Sofa Corner.glb"
  },
  {
    "pack": "furniture",
    "file": "Lounge Sofa Long.glb"
  },
  {
    "pack": "furniture",
    "file": "Lounge Sofa Ottoman.glb"
  },
  {
    "pack": "furniture",
    "file": "Lounge Sofa.glb"
  },
  {
    "pack": "furniture",
    "file": "Paneling.glb"
  },
  {
    "pack": "furniture",
    "file": "PingPongTable.glb"
  },
  {
    "pack": "furniture",
    "file": "Plant Small.glb"
  },
  {
    "pack": "furniture",
    "file": "Potted Plant.glb"
  },
  {
    "pack": "furniture",
    "file": "Radio.glb"
  },
  {
    "pack": "furniture",
    "file": "Round Table.glb"
  },
  {
    "pack": "furniture",
    "file": "Rug Doormat.glb"
  },
  {
    "pack": "furniture",
    "file": "Rug Rectangle.glb"
  },
  {
    "pack": "furniture",
    "file": "Rug Round.glb"
  },
  {
    "pack": "furniture",
    "file": "Rug Rounded.glb"
  },
  {
    "pack": "furniture",
    "file": "Rug Square.glb"
  },
  {
    "pack": "furniture",
    "file": "Shower Round.glb"
  },
  {
    "pack": "furniture",
    "file": "Side Table Drawers.glb"
  },
  {
    "pack": "furniture",
    "file": "Side Table.glb"
  },
  {
    "pack": "furniture",
    "file": "Speaker Small.glb"
  },
  {
    "pack": "furniture",
    "file": "Speaker.glb"
  },
  {
    "pack": "furniture",
    "file": "Stairs Corner.glb"
  },
  {
    "pack": "furniture",
    "file": "Stairs Open Single.glb"
  },
  {
    "pack": "furniture",
    "file": "Stairs Open.glb"
  },
  {
    "pack": "furniture",
    "file": "Stairs.glb"
  },
  {
    "pack": "furniture",
    "file": "Stool Bar Square.glb"
  },
  {
    "pack": "furniture",
    "file": "Table Coffee Glass.glb"
  },
  {
    "pack": "furniture",
    "file": "Table Coffee Square.glb"
  },
  {
    "pack": "furniture",
    "file": "Table Coffee.glb"
  },
  {
    "pack": "furniture",
    "file": "Table Cross Cloth.glb"
  },
  {
    "pack": "furniture",
    "file": "Table Cross.glb"
  },
  {
    "pack": "furniture",
    "file": "Table.glb"
  },
  {
    "pack": "furniture",
    "file": "TableJeremy.glb"
  },
  {
    "pack": "furniture",
    "file": "Television Vintage.glb"
  },
  {
    "pack": "furniture",
    "file": "Television.glb"
  },
  {
    "pack": "furniture",
    "file": "Toaster.glb"
  },
  {
    "pack": "furniture",
    "file": "Toilet Square.glb"
  },
  {
    "pack": "furniture",
    "file": "Toilet.glb"
  },
  {
    "pack": "furniture",
    "file": "Trashcan.glb"
  },
  {
    "pack": "furniture",
    "file": "Wall Doorway Wide.glb"
  },
  {
    "pack": "furniture",
    "file": "Wall Doorway.glb"
  },
  {
    "pack": "furniture",
    "file": "Wall Window.glb"
  },
  {
    "pack": "furniture",
    "file": "Washer.glb"
  },
  {
    "pack": "nature",
    "file": "Grass Blades.glb"
  },
  {
    "pack": "nature",
    "file": "Grass Clump.glb"
  },
  {
    "pack": "nature",
    "file": "Grass Green.glb"
  },
  {
    "pack": "space",
    "file": "Astronaut.glb"
  },
  {
    "pack": "space",
    "file": "Base Large.glb"
  },
  {
    "pack": "space",
    "file": "Bush.glb"
  },
  {
    "pack": "space",
    "file": "Grass.glb"
  },
  {
    "pack": "space",
    "file": "House Cylinder.glb"
  },
  {
    "pack": "space",
    "file": "House Long.glb"
  },
  {
    "pack": "space",
    "file": "House Open.glb"
  },
  {
    "pack": "space",
    "file": "House Pod.glb"
  },
  {
    "pack": "space",
    "file": "House Single Support.glb"
  },
  {
    "pack": "space",
    "file": "House Single.glb"
  },
  {
    "pack": "space",
    "file": "Plant 2.glb"
  },
  {
    "pack": "space",
    "file": "Plant.glb"
  },
  {
    "pack": "space",
    "file": "Rock Large.glb"
  },
  {
    "pack": "space",
    "file": "Rock.glb"
  },
  {
    "pack": "space",
    "file": "Rover.glb"
  },
  {
    "pack": "space",
    "file": "Tree Blob.glb"
  },
  {
    "pack": "space",
    "file": "Tree Floating.glb"
  },
  {
    "pack": "space",
    "file": "Tree Lava.glb"
  },
  {
    "pack": "space",
    "file": "Tree Light.glb"
  },
  {
    "pack": "space",
    "file": "Tree Spikes.glb"
  },
  {
    "pack": "space",
    "file": "Tree Spiral.glb"
  },
  {
    "pack": "space",
    "file": "Tree Swirl.glb"
  },
  {
    "pack": "trees",
    "file": "Birch Tree.glb"
  },
  {
    "pack": "trees",
    "file": "Pine Tree.glb"
  },
  {
    "pack": "trees",
    "file": "Simple Tree.glb"
  },
  {
    "pack": "trees",
    "file": "Stylized Tree.glb"
  }
] as const;
